apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: ical-service
  name: ical-service
spec:
  ports:
    - name: "7077"
      port: 7077
      targetPort: 7077
  selector:
    io.kompose.service: ical-service
