name: Build Nix targets

on:
  push:
    branches: ["nixx"]

env:
  REGISTRY: ghcr.io

jobs:
  build:
    name: Build Nix targets
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Nix Store Permissions
        run: |
          sudo mkdir -p /nix
          sudo chown -R runner:runner /nix
      - name: Build default package
        run: nix build ".#image"
      - id: repository
        name: Registry String
        uses: vishalmamidi/lowercase-action@v1
        with:
          string: ${{ env.REGISTRY}}/${{ github.repository }}
      - name: Pushing Image to GHCR
        run: |
          echo "Pushing to ${{ steps.repository.outputs.lowercase }}:latest"
          skopeo copy --dest-creds ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} docker-archive:./result docker://${{ steps.repository.outputs.lowercase }}-nix:latest